name: Compile LaTeX documents
on:
  push:
    paths:
      - '**/*.tex'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Identify changed files
      id: changes
      run: |
        files=$(git diff --name-only HEAD^ HEAD || git diff --name-only HEAD)
        echo "files=$(echo "$files" | grep '.tex' || echo '')" >> $GITHUB_ENV

    - name: Compile LaTeX documents
      if: env.files != ''
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ${{ env.files }}

    - name: Move PDFs to folder
      if: env.files != ''
      run: |
        for file in ${{ env.files }}; do
          pdf_file="${file%.tex}.pdf"
          mv "$pdf_file" "$(dirname "$file")/"
        done

    - name: Commit PDFs
      if: env.files != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f **/*.pdf
        git commit -m "chore: se agregan los PDFs compilados ♻️" || echo "No changes to commit"
        git push
