name: Compile LaTeX document
on:
  push:
    paths:
      - 'Resumen/Resumen01.tex'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: Resumen/Resumen01.tex

    - name: Move PDF to folder
      run: mv Resumen01.pdf Resumen/

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "Resumen/Resumen01.pdf"
        git commit -m "chore: se agrega el PDF compilado ♻️" || echo "No changes to commit"
        git push
